version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-container
    hostname: my-postgres-container
    environment:
      - POSTGRES_USER=team06
      - POSTGRES_PASSWORD=bdt2023_06
      - POSTGRES_DB=tubedb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    networks:
      - tfl-network

  redis:
    image: redis:latest
    container_name: my-redis-container
    hostname: my-redis-container
    ports:
      - '6379:6379'
    networks:
      - tfl-network

volumes:
  postgres-data:

networks:
  tfl-network:
    driver: bridge
